# Generated by Django 3.2.7 on 2021-10-15 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'category_av',
            },
        ),
        migrations.CreateModel(
            name='VendorAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
                ('category_av', models.ManyToManyField(related_name='vendors', to='using_api_view.CategoryAV')),
            ],
            options={
                'db_table': 'vendor_av',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100, unique=True)),
                ('category_av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='using_api_view.categoryav')),
            ],
            options={
                'db_table': 'sub_category_av',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('category_av', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='using_api_view.categoryav')),
            ],
            options={
                'db_table': 'delivery_av',
            },
        ),
    ]
